### ISSUE TITLE
What should be the value of `DATA_SIZE_ARB` for this module to be used in Kyber implementation

### ISSUE THREAD

**Issue by Sujjan19** [acmert/parametric-ntt#2]
I'm implementing Kyber-1024, so I've set the `RING_SIZE` to 256 & `PE_NUMBER` to 2, what should be the value of `DATA_SIZE_ARB` for the same. 
Also I already have the w values (twiddle factors) i.e. zetas ,required for Kyber how can i input them directly to the NTT module without testbench as such to read from txt file.

**Comment by acmert** [comment]
This HW does not support latest Kyber NTT operation (which uses an incomplete NTT without 2n-th root of unity). If you need NTT/polynomial multiplier circuit for Kyber, please check out the following repo:  https://github.com/acmert/kyber-polmul-hw

**Comment by Sujjan19** [comment]
Thank You
